### ISSUE TITLE
爬虫做种的时候报错

### ISSUE THREAD

**Issue by q1192589000** [k1995/BaiduyunSpider#10]
success to fetched hot users: 24
Traceback (most recent call last):
  File "spider.py", line 475, in <module>
    spider.seedUsers()
  File "spider.py", line 328, in seedUsers
    self.db.commit()
  File "spider.py", line 101, in commit
    self.dbconn.commit()
AttributeError: 'NoneType' object has no attribute 'commit'

请问有没有什么解决方法呢？
操作系统是用的 Centos 7X64
Python版本是：2.7.5

**Comment by saaak** [comment]
seedhotuser里有段代码有问题

**Comment by q1192589000** [comment]
现在估计也爬不了百度了

**Comment by k1995** [comment]
新版本正在开发中，dev分支。旧版本因百度API失效了，爬虫不可用

**Comment by q1192589000** [comment]
期待！！

**Comment by JackyKen** [comment]
现在新版本可用了吗

**Comment by k1995** [comment]
可以

**Comment by saaak** [comment]
> 可以

现在只能手动添加地址，不能自动爬？

**Comment by k1995** [comment]
emm.....开源版的目前是这样的

**Comment by saaak** [comment]
> emm.....开源版的目前是这样的

还有闭源版的吗

**Comment by saaak** [comment]
> emm.....开源版的目前是这样的

貌似百度把接口封了

**Comment by k1995** [comment]
有闭源版的，现在功能不太稳定，数据较少。百度把接口封了，只能自己做全网URL发现或者手动提交RL。

**Comment by saaak** [comment]
> 有闭源版的，现在功能不太稳定，数据较少。百度把接口封了，只能自己做全网URL发现或者手动提交URL。

闭源版以后会开源吗

**Comment by bytesniffer** [comment]
全网url 发现，大概怎么弄

**Comment by wwmxs** [comment]
1
