### ISSUE TITLE
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379.

### ISSUE THREAD

**Issue by lxqiong** [k1995/BaiduyunSpider#12]
按照你的步骤，执行。。是不是缺少了什么，
scrapy crawl baidupan 执行这个命令是一直报这个错

**Comment by k1995** [comment]
你没安装Redis，或者没启动

**Comment by bytesniffer** [comment]
参考　https://github.com/bytesniffer/BaiduyunSpider/tree/zdm 
我把依赖都docker 化了

**Comment by gityfx2018** [comment]
我也是抱着个错  执行完这个scrapy crawl baidupan就报上面的错

**Comment by gityfx2018** [comment]
我还是太菜了 依赖都装了还是不型
2019-08-15 16:31:45 [root] ERROR: 解析错误 https://pan.baidu.com/s/1sjta0od
Traceback (most recent call last):
  File "G:\google_download\yfx\vscode\BaiduyunSpider\spider\spiders\baidupan.py", line 26, in parse
    yield from self.parse_data(response)
  File "G:\google_download\yfx\vscode\BaiduyunSpider\spider\spiders\baidupan.py", line 33, in parse_data
    data = json.loads(re.search(pattern, response.text).group(1))
AttributeError: 'NoneType' object has no attribute 'group'
2019-08-15 16:32:39 [scrapy.extensions.logstats] INFO: Crawled 3 pages (at 1 pages/min), scraped 0 items (at 0 items/min)
